# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_sitemap', '0004_auto_20190504_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesitemapproperties',
            name='robots_extra',
            field=models.CharField(blank=True, default='', help_text='Extra values for robots meta tag', max_length=200, verbose_name='Extra robots value'),
        ),
    ]
